
image: python:3.5

pages:
  script:
    - pip install -U pip
    - pip install -r requirements.txt
    - make html
    - mv build/html/ public/
  artifacts:
    paths:
      - public
  only:
    - master
